version: '3.7'
services:
  init-gmail-bridge:
    volumes:
    - ./.matrix_bridge/:/bridge/
    - ./config.yaml:/gmail-config/gmail.config.yaml
    environment:
      GMAIL_BRIDGE_CONFIG_PATH: /gmail-config/gmail.config.yaml
    init: true
    depends_on: []
    network_mode: host
    entrypoint: []
    command:
    - /bin/sh
    - -c
    - rm -f /bridge/gmail_ping && /app/.venv/bin/python -m app.main hs_config | tee /bridge/gmail.yaml
      && chmod 666 /bridge/gmail.yaml && touch /bridge/gmail_ping
    build: 
      context: .
      dockerfile: Dockerfile-dev
  init-element:
    volumes:
    - ./.element_app:/new_app
    - ./dev_configs/element_config.json:/app/config.json
    init: true
    depends_on: []
    network_mode: host
    entrypoint: []
    command:
    - /bin/sh
    - -c
    - cp -r /app/* /new_app/ && rm -rf /new_app/config.json.gz && cd /new_app && gzip
      config.json && gzip -dk config.json.gz
    image: vectorim/element-web:latest
  init-config:
    volumes:
    - ./.matrix_app_data:/data
    - ./dev_configs/synapse-homeserver.yaml:/synapse-config/homeserver.yaml
    - ./dev_configs/synapse.log.config:/synapse-config/jif.one.log.config
    init: true
    depends_on: []
    network_mode: host
    entrypoint: []
    command:
    - /bin/sh
    - -c
    - cp /synapse-config/homeserver.yaml /data
      && cp /synapse-config/jif.one.log.config /data && mkdir -p /data/keys && chown
      -R 991:991 /data/keys && mkdir -p /data/media_store && chown -R 991:991 /data/media_store
      && mkdir -p /data/uploads && chown -R 991:991 /data/uploads && mkdir -p /data/db
      && chown -R 991:991 /data/db
    image: matrixdotorg/synapse:latest
  init-synapse:
    volumes:
    - ./.matrix_app_data:/data
    - ./.matrix_bridge/:/bridge/
    environment:
      SYNAPSE_SERVER_NAME: jif.one
      SYNAPSE_REPORT_STATS: 'no'
    init: true
    depends_on: []
    network_mode: host
    entrypoint: []
    command:
    - /bin/sh
    - -c
    - python -m synapse.app.homeserver --config-path /data/homeserver.yaml --keys-directory
      /data/keys --generate-keys
    image: matrixdotorg/synapse:latest
  synapse:
    volumes:
    - ./.matrix_app_data:/data
    - ./.matrix_bridge/:/bridge/
    environment:
      SYNAPSE_SERVER_NAME: jif.one
      SYNAPSE_REPORT_STATS: 'no'
      SYNAPSE_DATA_DIR: /data
    init: true
    depends_on:
    - init-gmail-bridge
    - init-element
    - init-config
    - init-synapse
    network_mode: host
    entrypoint: []
    command:
    - /bin/sh
    - -c
    - 'while [ ! -f /bridge/gmail_ping ]; do sleep 1 && echo waiting: gmail config;
      done && rm /bridge/gmail_ping && /start.py'
    image: matrixdotorg/synapse:latest
  element:
    volumes:
    - /element_app:/app
    environment: []
    init: true
    depends_on:
    - init-gmail-bridge
    - init-element
    - init-config
    - init-synapse
    network_mode: host
    image: vectorim/element-web:latest
  gmail-bridge:
    volumes:
    - ./.matrix_bridge/:/bridge/
    - gb-venv:/app/.venv
    - ./:/app
    - ./config.yaml:/gmail-config/gmail.config.yaml
    environment:
      GMAIL_BRIDGE_CONFIG_PATH: /gmail-config/gmail.config.yaml
    init: true
    depends_on:
    - init-gmail-bridge
    - init-element
    - init-config
    - init-synapse
    network_mode: host
    entrypoint: []
    command:
    - /bin/sh
    - -c
    - sleep infinity
    build: 
      context: .
      dockerfile: Dockerfile-dev

volumes:
  gb-venv: