# syntax=docker/dockerfile:1.2
FROM python:3.9
RUN useradd -ms /bin/bash dev && echo "dev:dev" | chpasswd
RUN mkdir -p /app && chmod a+rw /app
USER dev

	WORKDIR /app
	RUN pip3 install poetry
	COPY ./poetry.lock ./pyproject.toml /app/
	RUN --mount=type=cache,target=/home/dev/.cache/pip /home/dev/.local/bin/poetry config virtualenvs.in-project true && /home/dev/.local/bin/poetry install --no-ansi -n

	COPY ./app /app/app
USER root
	CMD ["/app/.venv/bin/python3", "-m", "app.main"]
