# .github/workflows/app.yaml
name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install poetry
        run: |
          python -m pip install --upgrade poetry wheel
      # - id: cache-poetry
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.local/share/virtualenvs
      #     key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        # if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          poetry config virtualenvs.create false
          poetry install --no-ansi -n
      - name: Run test suite
        run: |
          pytest -v
